
# --- Game env infos --- #
N_OBSERVATIONS = 301
N_ACTIONS = 268

# --- Cards actions --- #

# Card assignment actions
ACTION_CARD_ASSIGNMENT_CHOOSE_LEFT_AS_PATH = 0
ACTION_CARD_ASSIGNMENT_CHOOSE_RIGHT_AS_PATH = 1

# Left sheet actions
ACTION_ADVANCE_COHORT_LEFT = 2
ACTION_ADVANCE_COHORT_CENTER = 3
ACTION_ADVANCE_COHORT_RIGHT = 4
ACTION_ADVANCE_MINING_AND_FORESTING = 5
ACTION_ADVANCE_WALL_GUARD = 6
ACTION_ADVANCE_CIPPI = 7
ACTION_ADVANCE_WALL = 8
ACTION_ADVANCE_FORT_PAY_SOLDIER = 9
ACTION_ADVANCE_FORT_PAY_BUILDER = 10
ACTION_BUILD_SMALL_GRANARY = 11
ACTION_BUILD_LARGE_GRANARY = 12
ACTION_USE_TRAINING_GROUNDS = 13
ACTION_BUILD_SMALL_HOTEL = 14
ACTION_BUILD_LARGE_HOTEL = 15
ACTION_BUILD_SMALL_WORKSHOP = 16
ACTION_BUILD_LARGE_WORKSHOP = 17
ACTION_BUILD_SMALL_ROAD = 18
ACTION_BUILD_LARGE_ROAD = 19
ACTION_USE_FORUM_BUILDER_BUILDER_TO_SERVANT = 20
ACTION_USE_FORUM_BUILDER_BUILDER_TO_CIVILIAN = 21
ACTION_USE_FORUM_SERVANT_SERVANT_TO_BUILDER = 22
ACTION_USE_FORUM_SERVANT_SERVANT_TO_CIVILIAN = 23
ACTION_USE_FORUM_CIVILIAN_CIVILIAN_TO_BUILDER = 24
ACTION_USE_FORUM_CIVILIAN_CIVILIAN_TO_SERVANT = 25
ACTION_USE_FORUM_BUILDER_SERVANT_TO_CIVILIAN = 26
ACTION_USE_FORUM_BUILDER_CIVILIAN_TO_SERVANT = 27
ACTION_USE_FORUM_SERVANT_CIVILIAN_TO_BUILDER = 28
ACTION_BUILD_LANDMARK_1 = 29
ACTION_BUILD_LANDMARK_2 = 30
ACTION_BUILD_LANDMARK_3 = 31
ACTION_BUILD_LANDMARK_4 = 32

# Right sheet actions
# Traders
ACTION_ADVANCE_TRADERS_TRACK = 33
ACTION_BUILD_SMALL_PRECINCT = 34
ACTION_BUILD_MEDIUM_PRECINCT = 35
ACTION_BUILD_LARGE_PRECINCT = 36
ACTION_BUILD_MARKET = 37
ACTION_BUY_GOODS_FATE_CARD = 38
ACTION_BUY_GOODS_NEIGHBOR_CARD_1 = 39
ACTION_BUY_GOODS_NEIGHBOR_CARD_2 = 40
ACTION_BUY_GOODS_7_FATE_CARD = 41
ACTION_BUY_GOODS_7_NEIGHBOR_CARD_1 = 42
ACTION_BUY_GOODS_7_NEIGHBOR_CARD_2 = 43
ACTION_BUY_GOODS_8_FATE_CARD = 44
ACTION_BUY_GOODS_8_NEIGHBOR_CARD_1 = 45
ACTION_BUY_GOODS_8_NEIGHBOR_CARD_2 = 46

# Performers
ACTION_ADVANCE_PERFORMERS_TRACK = 47
ACTION_BUILD_THEATER = 48
ACTION_ARRANGE_PERFORMANCE_1 = 49
ACTION_ARRANGE_PERFORMANCE_2 = 50
ACTION_ARRANGE_PERFORMANCE_3 = 51
ACTION_ARRANGE_PERFORMANCE_4 = 52
ACTION_ARRANGE_PERFORMANCE_5 = 53
ACTION_ARRANGE_PERFORMANCE_6 = 54
ACTION_BUILD_COLOSSEUM = 55
ACTION_TRAIN_GLADIATOR_1_SERVANT = 56
ACTION_TRAIN_GLADIATOR_1_SERVANT_AND_FIGHT = 57
ACTION_TRAIN_GLADIATOR_1_CIVILIAN = 58
ACTION_TRAIN_GLADIATOR_1_CIVILIAN_AND_FIGHT = 59
ACTION_TRAIN_GLADIATOR_2_SERVANT = 60
ACTION_TRAIN_GLADIATOR_2_SERVANT_AND_FIGHT = 61
ACTION_TRAIN_GLADIATOR_2_CIVILIAN = 62
ACTION_TRAIN_GLADIATOR_2_CIVILIAN_AND_FIGHT = 63

# Priests
ACTION_ADVANCE_PRIESTS_TRACK = 64
ACTION_BUILD_SMALL_GARDEN = 65
ACTION_BUILD_LARGE_GARDEN = 66
ACTION_BUILD_SMALL_TEMPLE = 67
ACTION_FILL_SMALL_TEMPLE_SOLDIER = 68
ACTION_FILL_SMALL_TEMPLE_BUILDER = 69
ACTION_FILL_SMALL_TEMPLE_SERVANT = 70
ACTION_FILL_SMALL_TEMPLE_CIVILIAN = 71
ACTION_BUILD_MEDIUM_TEMPLE = 72
ACTION_FILL_MEDIUM_TEMPLE_SOLDIER = 73
ACTION_FILL_MEDIUM_TEMPLE_BUILDER = 74
ACTION_FILL_MEDIUM_TEMPLE_SERVANT = 75
ACTION_FILL_MEDIUM_TEMPLE_CIVILIAN = 76
ACTION_BUILD_LARGE_TEMPLE = 77
ACTION_FILL_LARGE_TEMPLE_SOLDIER = 78
ACTION_FILL_LARGE_TEMPLE_BUILDER = 79
ACTION_FILL_LARGE_TEMPLE_SERVANT = 80
ACTION_FILL_LARGE_TEMPLE_CIVILIAN = 81

# Apparitores
ACTION_ADVANCE_APPARITORES_TRACK = 82
ACTION_BUILD_BATHS = 83
ACTION_PAY_BRIBE = 84
ACTION_BUILD_COURTHOUSE = 85
ACTION_COURTHOUSE_GET_SERVANT = 86
ACTION_COURTHOUSE_BUILDER_TO_TWO_SERVANTS = 87
ACTION_COURTHOUSE_SERVANT_TO_BUILDER = 88

# Patricians
ACTION_ADVANCE_PATRICIANS_TRACK = 89
ACTION_SEND_LEFT_DIPLOMAT = 90
ACTION_SEND_CENTER_DIPLOMAT = 91
ACTION_SEND_RIGHT_DIPLOMAT = 92
ACTION_SEND_SCOUT_PROSPECT_CARD = 93
ACTION_SEND_SCOUT_NEIGHBOR_CARD_1 = 94
ACTION_SEND_SCOUT_NEIGHBOR_CARD_2 = 95
# Pattern 1 (12 positions)
# XX
# XX
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_0_0 = 96
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_0_1 = 97
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_0_2 = 98
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_0_3 = 99
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_1_0 = 100
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_1_1 = 101
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_1_2 = 102
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_1_3 = 103
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_2_0 = 104
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_2_1 = 105
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_2_2 = 106
ACTION_PLACE_SCOUT_PATTERN_1_POSITION_2_3 = 107
# Pattern 2 (13 positions)
# XXXX
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_0 = 108
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_1 = 109
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_1_0 = 110
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_1_1 = 111
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_2_0 = 112
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_2_1 = 113
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_3_0 = 114
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_3_1 = 115
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_0_90 = 116
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_1_90 = 117
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_2_90 = 118
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_3_90 = 119
ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_4_90 = 120
# Pattern 3 (34 positions)
# XX
#  XX
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_0 = 121
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_1 = 122
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_2 = 123
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_0 = 124
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_1 = 125
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_2 = 126
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_0 = 127
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_1 = 128
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_2 = 129
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_0_M = 130
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_1_M = 131
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_2_M = 132
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_0_M = 133
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_1_M = 134
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_2_M = 135
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_0_M = 136
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_1_M = 137
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_2_M = 138
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_0_90 = 139
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_1_90 = 140
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_2_90 = 141
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_3_90 = 142
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_0_90 = 143
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_1_90 = 144
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_2_90 = 145
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_3_90 = 146
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_0_90_M = 147
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_1_90_M = 148
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_2_90_M = 149
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_3_90_M = 150
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_0_90_M = 151
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_1_90_M = 152
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_2_90_M = 153
ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_3_90_M = 154
# Pattern 4 (34 positions)
#  XXX
#   X
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_0 = 155
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_1 = 156
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_2 = 157
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_0 = 158
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_1 = 159
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_2 = 160
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_0 = 161
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_1 = 162
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_2 = 163
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_0_M = 164
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_1_M = 165
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_2_M = 166
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_0_M = 167
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_1_M = 168
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_2_M = 169
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_0_M = 170
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_1_M = 171
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_2_M = 172
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_0_90 = 173
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_1_90 = 174
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_2_90 = 175
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_3_90 = 176
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_0_90 = 177
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_1_90 = 178
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_2_90 = 179
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_3_90 = 180
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_0_90_M = 181
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_1_90_M = 182
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_2_90_M = 183
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_3_90_M = 184
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_0_90_M = 185
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_1_90_M = 186
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_2_90_M = 187
ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_3_90_M = 188
# Pattern 5 (68 positions)
# XXX
# X
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0 = 189
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1 = 190
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2 = 191
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0 = 192
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1 = 193
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2 = 194
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_0 = 195
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_1 = 196
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_2 = 197
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_M = 198
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_M = 199
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_M = 200
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_M = 201
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_M = 202
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_M = 203
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_0_M = 204
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_1_M = 205
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_2_M = 206
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_180 = 207
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_180 = 208
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_180 = 209
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_180 = 210
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_180 = 211
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_180 = 212
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_0_180 = 213
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_1_180 = 214
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_2_180 = 215
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_180_M = 216
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_180_M = 217
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_180_M = 218
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_180_M = 219
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_180_M = 220
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_180_M = 221
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_0_180_M = 222
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_1_180_M = 223
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_2_180_M = 224
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_90 = 225
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_90 = 226
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_90 = 227
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_3_90 = 228
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_90 = 229
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_90 = 230
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_90 = 231
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_3_90 = 232
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_90_M = 233
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_90_M = 234
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_90_M = 235
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_3_90_M = 236
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_90_M = 237
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_90_M = 238
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_90_M = 239
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_3_90_M = 240
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_270 = 241
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_270 = 242
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_270 = 243
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_3_270 = 244
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_270 = 245
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_270 = 246
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_270 = 247
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_3_270 = 248
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_270_M = 249
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_270_M = 250
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_270_M = 251
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_3_270_M = 252
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_270_M = 253
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_270_M = 254
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_270_M = 255
ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_3_270_M = 256

# Follow up actions
ACTION_RECEIVE_ATTRIBUTE_RENOWN = 257
ACTION_RECEIVE_ATTRIBUTE_PIETY = 258
ACTION_RECEIVE_ATTRIBUTE_VALOUR = 259
ACTION_RECEIVE_ATTRIBUTE_DISCIPLINE = 260
ACTION_USE_LEFT_FAVOUR = 261
ACTION_USE_CENTER_FAVOUR = 262
ACTION_USE_RIGHT_FAVOUR = 263
ACTION_USE_GENERAL_FAVOUR_LEFT = 264
ACTION_USE_GENERAL_FAVOUR_CENTER = 265
ACTION_USE_GENERAL_FAVOUR_RIGHT = 266

# End round action
ACTION_END_ROUND = 267

# Groups
ACTIONS_CARD_ASSIGNMENT = [
    ACTION_CARD_ASSIGNMENT_CHOOSE_LEFT_AS_PATH,
    ACTION_CARD_ASSIGNMENT_CHOOSE_RIGHT_AS_PATH
]

ACTIONS_LEFT_SHEET = [
    ACTION_ADVANCE_COHORT_LEFT,
    ACTION_ADVANCE_COHORT_CENTER,
    ACTION_ADVANCE_COHORT_RIGHT,
    ACTION_ADVANCE_MINING_AND_FORESTING,
    ACTION_ADVANCE_WALL_GUARD,
    ACTION_ADVANCE_CIPPI,
    ACTION_ADVANCE_WALL,
    ACTION_ADVANCE_FORT_PAY_SOLDIER,
    ACTION_ADVANCE_FORT_PAY_BUILDER,
    ACTION_USE_TRAINING_GROUNDS,
    ACTION_BUILD_SMALL_GRANARY,
    ACTION_BUILD_LARGE_GRANARY,
    ACTION_BUILD_SMALL_HOTEL,
    ACTION_BUILD_LARGE_HOTEL,
    ACTION_BUILD_SMALL_WORKSHOP,
    ACTION_BUILD_LARGE_WORKSHOP,
    ACTION_BUILD_SMALL_ROAD,
    ACTION_BUILD_LARGE_ROAD,
    ACTION_USE_FORUM_BUILDER_BUILDER_TO_SERVANT,
    ACTION_USE_FORUM_BUILDER_BUILDER_TO_CIVILIAN,
    ACTION_USE_FORUM_SERVANT_SERVANT_TO_BUILDER,
    ACTION_USE_FORUM_SERVANT_SERVANT_TO_CIVILIAN,
    ACTION_USE_FORUM_CIVILIAN_CIVILIAN_TO_BUILDER,
    ACTION_USE_FORUM_CIVILIAN_CIVILIAN_TO_SERVANT,
    ACTION_USE_FORUM_BUILDER_SERVANT_TO_CIVILIAN,
    ACTION_USE_FORUM_BUILDER_CIVILIAN_TO_SERVANT,
    ACTION_USE_FORUM_SERVANT_CIVILIAN_TO_BUILDER ,
    ACTION_BUILD_LANDMARK_1,
    ACTION_BUILD_LANDMARK_2,
    ACTION_BUILD_LANDMARK_3,
    ACTION_BUILD_LANDMARK_4,
]

ACTIONS_ADVANCE_COHORT = [
    ACTION_ADVANCE_COHORT_LEFT,
    ACTION_ADVANCE_COHORT_CENTER,
    ACTION_ADVANCE_COHORT_RIGHT,
]

ACTIONS_TRADERS = [
    ACTION_ADVANCE_TRADERS_TRACK,
    ACTION_BUILD_SMALL_PRECINCT,
    ACTION_BUILD_MEDIUM_PRECINCT,
    ACTION_BUILD_LARGE_PRECINCT,
    ACTION_BUILD_MARKET,
    ACTION_BUY_GOODS_FATE_CARD,
    ACTION_BUY_GOODS_NEIGHBOR_CARD_1,
    ACTION_BUY_GOODS_NEIGHBOR_CARD_2,
    ACTION_BUY_GOODS_7_FATE_CARD,
    ACTION_BUY_GOODS_7_NEIGHBOR_CARD_1,
    ACTION_BUY_GOODS_7_NEIGHBOR_CARD_2,
    ACTION_BUY_GOODS_8_FATE_CARD,
    ACTION_BUY_GOODS_8_NEIGHBOR_CARD_1,
    ACTION_BUY_GOODS_8_NEIGHBOR_CARD_2,
]

ACTIONS_TRADERS_MARKET = [
    ACTION_BUY_GOODS_FATE_CARD,
    ACTION_BUY_GOODS_NEIGHBOR_CARD_1,
    ACTION_BUY_GOODS_NEIGHBOR_CARD_2,
    ACTION_BUY_GOODS_7_FATE_CARD,
    ACTION_BUY_GOODS_7_NEIGHBOR_CARD_1,
    ACTION_BUY_GOODS_7_NEIGHBOR_CARD_2,
    ACTION_BUY_GOODS_8_FATE_CARD,
    ACTION_BUY_GOODS_8_NEIGHBOR_CARD_1,
    ACTION_BUY_GOODS_8_NEIGHBOR_CARD_2,
]

ACTIONS_PERFORMERS = [
    ACTION_ADVANCE_PERFORMERS_TRACK,
    ACTION_BUILD_THEATER,
    ACTION_ARRANGE_PERFORMANCE_1,
    ACTION_ARRANGE_PERFORMANCE_2,
    ACTION_ARRANGE_PERFORMANCE_3,
    ACTION_ARRANGE_PERFORMANCE_4,
    ACTION_ARRANGE_PERFORMANCE_5,
    ACTION_ARRANGE_PERFORMANCE_6,
    ACTION_BUILD_COLOSSEUM,
    ACTION_TRAIN_GLADIATOR_1_SERVANT,
    ACTION_TRAIN_GLADIATOR_1_SERVANT_AND_FIGHT,
    ACTION_TRAIN_GLADIATOR_1_CIVILIAN,
    ACTION_TRAIN_GLADIATOR_1_CIVILIAN_AND_FIGHT,
    ACTION_TRAIN_GLADIATOR_2_SERVANT,
    ACTION_TRAIN_GLADIATOR_2_SERVANT_AND_FIGHT,
    ACTION_TRAIN_GLADIATOR_2_CIVILIAN,
    ACTION_TRAIN_GLADIATOR_2_CIVILIAN_AND_FIGHT,
]

ACTIONS_PERFORMERS_THEATER = [
    ACTION_ARRANGE_PERFORMANCE_1,
    ACTION_ARRANGE_PERFORMANCE_2,
    ACTION_ARRANGE_PERFORMANCE_3,
    ACTION_ARRANGE_PERFORMANCE_4,
    ACTION_ARRANGE_PERFORMANCE_5,
    ACTION_ARRANGE_PERFORMANCE_6,
]

ACTIONS_PRIESTS = [
    ACTION_ADVANCE_PRIESTS_TRACK,
    ACTION_BUILD_SMALL_GARDEN,
    ACTION_BUILD_LARGE_GARDEN,
    ACTION_BUILD_SMALL_TEMPLE,
    ACTION_FILL_SMALL_TEMPLE_SOLDIER,
    ACTION_FILL_SMALL_TEMPLE_BUILDER,
    ACTION_FILL_SMALL_TEMPLE_SERVANT,
    ACTION_FILL_SMALL_TEMPLE_CIVILIAN,
    ACTION_BUILD_MEDIUM_TEMPLE,
    ACTION_FILL_MEDIUM_TEMPLE_SOLDIER,
    ACTION_FILL_MEDIUM_TEMPLE_BUILDER,
    ACTION_FILL_MEDIUM_TEMPLE_SERVANT,
    ACTION_FILL_MEDIUM_TEMPLE_CIVILIAN,
    ACTION_BUILD_LARGE_TEMPLE,
    ACTION_FILL_LARGE_TEMPLE_SOLDIER,
    ACTION_FILL_LARGE_TEMPLE_BUILDER,
    ACTION_FILL_LARGE_TEMPLE_SERVANT,
    ACTION_FILL_LARGE_TEMPLE_CIVILIAN,
]

ACTIONS_APPARITORES = [
    ACTION_ADVANCE_APPARITORES_TRACK,
    ACTION_BUILD_BATHS,
    ACTION_PAY_BRIBE,
    ACTION_BUILD_COURTHOUSE,
    ACTION_COURTHOUSE_GET_SERVANT,
    ACTION_COURTHOUSE_BUILDER_TO_TWO_SERVANTS,
    ACTION_COURTHOUSE_SERVANT_TO_BUILDER,
]

ACTIONS_SCOUTS_PATTERN_1 = [
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_0_0,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_0_1,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_0_2,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_0_3,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_1_0,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_1_1,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_1_2,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_1_3,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_2_0,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_2_1,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_2_2,
    ACTION_PLACE_SCOUT_PATTERN_1_POSITION_2_3,
]

ACTIONS_SCOUTS_PATTERN_2 = [
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_0,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_1,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_1_0,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_1_1,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_2_0,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_2_1,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_3_0,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_3_1,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_0_90,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_1_90,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_2_90,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_3_90,
    ACTION_PLACE_SCOUT_PATTERN_2_POSITION_0_4_90,
]

ACTIONS_SCOUTS_PATTERN_3 = [
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_0,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_1,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_2,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_0,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_1,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_2,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_0,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_1,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_2,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_0_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_1_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_2_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_0_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_1_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_2_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_0_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_1_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_2_2_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_0_90,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_1_90,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_2_90,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_3_90,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_0_90,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_1_90,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_2_90,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_3_90,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_0_90_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_1_90_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_2_90_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_0_3_90_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_0_90_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_1_90_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_2_90_M,
    ACTION_PLACE_SCOUT_PATTERN_3_POSITION_1_3_90_M,
]

ACTIONS_SCOUTS_PATTERN_4 = [
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_0,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_1,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_2,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_0,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_1,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_2,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_0,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_1,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_2,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_0_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_1_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_2_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_0_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_1_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_2_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_0_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_1_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_2_2_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_0_90,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_1_90,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_2_90,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_3_90,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_0_90,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_1_90,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_2_90,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_3_90,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_0_90_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_1_90_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_2_90_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_0_3_90_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_0_90_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_1_90_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_2_90_M,
    ACTION_PLACE_SCOUT_PATTERN_4_POSITION_1_3_90_M,
]

ACTIONS_SCOUTS_PATTERN_5 = [
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_0,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_1,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_2,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_0_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_1_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_2_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_0_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_1_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_2_180,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_0_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_1_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_2_2_180_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_90,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_90,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_90,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_3_90,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_90,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_90,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_90,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_3_90,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_90_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_90_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_90_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_3_90_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_90_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_90_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_90_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_3_90_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_270,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_270,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_270,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_3_270,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_270,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_270,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_270,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_3_270,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_0_270_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_1_270_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_2_270_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_0_3_270_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_0_270_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_1_270_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_2_270_M,
    ACTION_PLACE_SCOUT_PATTERN_5_POSITION_1_3_270_M,
]

ACTIONS_SCOUTS = ACTIONS_SCOUTS_PATTERN_1 + \
    ACTIONS_SCOUTS_PATTERN_2 + \
    ACTIONS_SCOUTS_PATTERN_3 + \
    ACTIONS_SCOUTS_PATTERN_4 + \
    ACTIONS_SCOUTS_PATTERN_5

ACTIONS_PATRICIANS = [
    ACTION_ADVANCE_PATRICIANS_TRACK,
    ACTION_SEND_LEFT_DIPLOMAT,
    ACTION_SEND_CENTER_DIPLOMAT,
    ACTION_SEND_RIGHT_DIPLOMAT,
    ACTION_SEND_SCOUT_PROSPECT_CARD,
    ACTION_SEND_SCOUT_NEIGHBOR_CARD_1,
    ACTION_SEND_SCOUT_NEIGHBOR_CARD_2,
] + ACTIONS_SCOUTS

ACTIONS_RIGHT_SHEET = ACTIONS_TRADERS + \
    ACTIONS_PERFORMERS + \
    ACTIONS_PRIESTS + \
    ACTIONS_APPARITORES + \
    ACTIONS_PATRICIANS

ACTIONS_FOLLOW_UP = [
    ACTION_RECEIVE_ATTRIBUTE_RENOWN,
    ACTION_RECEIVE_ATTRIBUTE_PIETY,
    ACTION_RECEIVE_ATTRIBUTE_VALOUR,
    ACTION_RECEIVE_ATTRIBUTE_DISCIPLINE,
    ACTION_USE_LEFT_FAVOUR,
    ACTION_USE_CENTER_FAVOUR,
    ACTION_USE_RIGHT_FAVOUR,
    ACTION_USE_GENERAL_FAVOUR_LEFT,
    ACTION_USE_GENERAL_FAVOUR_CENTER,
    ACTION_USE_GENERAL_FAVOUR_RIGHT,
]

ALL_ACTIONS = ACTIONS_CARD_ASSIGNMENT + \
    ACTIONS_LEFT_SHEET + \
    ACTIONS_RIGHT_SHEET + \
    ACTIONS_SCOUTS + \
    ACTIONS_FOLLOW_UP + \
    [ACTION_END_ROUND]